# Generated by Django 4.2.3 on 2024-02-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
                ("datetime_added", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Redact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("string", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True)),
                ("reporter", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("pool_report", models.BooleanField()),
                ("publish", models.BooleanField()),
                ("off_the_record", models.BooleanField()),
                (
                    "review_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Complete"),
                        ],
                        default="Unspecified",
                        verbose_name="Editorial Review",
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
                ("body_original", models.TextField(blank=True, null=True)),
                ("body_clean", models.TextField(blank=True, null=True)),
                ("body_redact", models.TextField(blank=True, null=True)),
                ("body_final", models.TextField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing.batch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_disposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "disposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file", models.FileField(upload_to="files")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing.item",
                    ),
                ),
            ],
        ),
    ]
