# Generated by Django 4.2.3 on 2024-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0002_batch_redact_item_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Redact",
        ),
    ]
