# Generated by Django 4.2.3 on 2023-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_batch_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
