# Generated by Django 4.2.3 on 2023-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_item_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
