# Generated by Django 4.2.3 on 2024-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_delete_redact"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="last_export",
            field=models.DateTimeField(null=True),
        ),
    ]
