# Generated by Django 4.2.3 on 2023-08-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_rename_redaction_review_item_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedStrings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='comment',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='batch',
            name='datetime_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='body_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
