# Generated by Django 4.2.3 on 2023-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_redactedstrings_rename_comment_item_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string', models.JSONField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RedactedStrings',
        ),
    ]
