# Generated by Django 4.2.3 on 2024-05-20 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0007_alter_batch_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
