# Generated by Django 4.2.3 on 2023-08-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_redact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redact',
            name='number',
        ),
        migrations.AddField(
            model_name='redact',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
