# Generated by Django 4.2.3 on 2023-08-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_remove_redact_number_redact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reporter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
