# Generated by Django 4.2.3 on 2023-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_alter_item_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='reporter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
