# Generated by Django 4.2.3 on 2023-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_alter_item_date_alter_item_reporter_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reporter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
