# Generated by Django 4.2.3 on 2023-09-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_alter_item_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='review_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Complete')]),
        ),
    ]
