# Generated by Django 4.2.3 on 2023-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_alter_item_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='review_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Complete')], default='Unspecified', verbose_name='Editorial Review'),
        ),
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.ManyToManyField(to='processing.file'),
        ),
    ]
