# Generated by Django 4.2.3 on 2023-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_file_alter_item_review_status_item_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='files',
        ),
    ]
