# Generated by Django 4.2.3 on 2023-11-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0016_file_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.item'),
        ),
    ]
