# Generated by Django 4.2.3 on 2024-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0021_file_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1000, upload_to='files'),
        ),
    ]
